<h1 style="text-align:center;" align="center">
  <b><span style="font-family:等线;font-weight:bold;font-size:15.0000pt;"><span>员工保密协议</span></span></b><b><span style="font-family:Calibri;font-weight:bold;font-size:15.0000pt;"></span></b>
</h1>
<p class="p" style="text-indent:0.0000pt;text-align:center;background:#FFFFFF;" align="center">
  <b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>前</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;">&nbsp;&nbsp;</span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>言</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"></span></b>
</p>
<p class="p" style="text-indent:24.0000pt;background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您即将登陆</span>“宇培国际控股项目管理系统”（http://60.169.89.153:88/zentao），为宇培供应链管理集团有限公司及其控股子公司、关联公司（以下简称“公司”）</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>提供服务和履行职务，已经</span>(或将要)知悉</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>的商业秘密。为了明确</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>的保密义务，有效保护</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>的商业秘密，防止该商业秘密被公开披露或以任何形式泄漏，根据《中华人民共和国合同法》、《中华人民共和国劳动法》、《中华人民共和国反不正当竞争法》</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>之规定制定</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>本</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>《员工保密协议》（以下简称本协议）</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"></span>
</p>
<p class="p" style="text-indent:24.0000pt;background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>本协议与您在职及离职后的保密义务息息相关，</span></span><b><u><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;text-decoration:underline;font-size:12.0000pt;background:#FFFFFF;"><span>请您登陆系统前，请务必完整阅读并透彻理解公司的保密政策。公司再次提醒：如您在登陆页面上勾选</span>“我已阅读并同意《员工保密协议》”即视为您已完全知悉本协议的全部内容，并同意按本协议之约定履行相应的保密义务</span></u></b><u><span style="font-family:宋体;color:#2B2B2B;text-decoration:underline;font-size:12.0000pt;background:#FFFFFF;"><span>。</span></span></u><b><u><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;text-decoration:underline;font-size:12.0000pt;background:#FFFFFF;"><span>本协议将于您点击</span>“登录”时生效。</span></u></b><u><span style="font-family:宋体;color:#2B2B2B;text-decoration:underline;font-size:12.0000pt;background:#FFFFFF;"></span></u>
</p>
<p class="p" style="text-align:center;background:#FFFFFF;" align="center">
  <b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>第</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>一</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>章</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;">&nbsp;&nbsp;</span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>商业秘密的范围</span></span></b><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>：</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">1、</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>本协议</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>所称</span>“商业秘密”包括但不限于：技术信息、专有技术、</span><span style="font-family:等线;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>客户信息、</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>内部秘密等。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>对此商业秘密承担保密义务。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:等线;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>（</span>1<span>）</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>技术信息包括但不限于：技术方案、计算机软件、数据库、软件源码、生产数据、测试数据；项目在规划、需求、设计、编码、测试、实施等各阶段产生的各类文档、项目计划、配置信息、工作日志、会议记录、评审记录、项目周报、项目总结、模板等；供应商名单、解决方案、软硬件清单、软硬件配置文件、运维制度、巡检记录、故障记录、历史备份等；实施计划、实施方案、培训材料、问题清单、</span>SOP文档、KPI文档等。</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:等线;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>（</span>2<span>）</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>专有技术是指</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>软件研发过程中的信息、资料、流程、经验、方法或其组合，并且未在任何地方公开过其完整形式的、未作为产权来保护的其他技术。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:等线;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>（</span>3<span>）</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>客户信息包括但不限于：客户的姓名、性别、身份证信息、手机号码、家庭住址、工作单位、购票相关信息、乘车相关信息、个人需求、录音等信息、文件、资料、图表、报告、信件、传真、磁带、磁盘、以及其他任何形式的载体，而且无论这些信息有无商业价值。无论客户是否基于对</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>个人的信赖而与</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>进行市场交易，也无论客户是否自愿选择与</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>或者</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>离职后的新单位进行市场交易，</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>在任职期间或者离职后非因履行</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>职务使用</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>的客户名单均视为侵犯</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>商业秘密。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:等线;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>（</span>4<span>）</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>内部秘密包括但不限于：</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>的各种规章制度、内部文件、营销策略、推广计划、合作渠道、</span></span><span style="font-family:等线;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>对外投融资、</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>业务报表或数据、公司档案、财务资料、法律事务信息、人力资源信息</span></span><span style="font-family:等线;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>（包括但不限于</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>员工结构及薪资结构信息）、内网信息、内部邮件等不宜对外公开的信息。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">2.同时，在</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>生产或者经营中，某一信息的泄露可能造成下述后果之一的，该信息也属于</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>商业秘密：</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:等线;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>（</span>1<span>）</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>影响</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>生产、营销、稳定、安全或者发展的；</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:等线;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>（</span>2<span>）</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>影响</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>技术进步的；</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:等线;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>（</span>3<span>）</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>使</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>利益受到损害，或者使</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>在商业竞争中处于被动或不利地位的；</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:等线;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>（</span>4<span>）</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>影响</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>对外交流或商业谈判顺利进行的；</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:等线;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>（</span>5<span>）</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>影响</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>对外承担保密义务的。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">3.</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>在记录某一技术信息或者经营信息的载体上注明</span>“保密”或“内部资料”等字样，或者载明保密等级的，该信息属于商业秘密。</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">4.</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>本协议</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>所称商业秘密，也包括虽属于第三方但</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>承诺有保密义务的商业秘密。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="text-align:center;background:#FFFFFF;" align="center">
  <b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>第</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>二</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>章</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;">&nbsp;&nbsp;</span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>商业秘密的载体</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;"></span></b>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">1、</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>持有或保管的一切记录有</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>商业秘密信息的文件、资料、图表、笔记、报告、信件、传真、磁带、磁盘、仪器、电子邮件以及其它任何形式的载体均归</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>所有，无论这些信息有无商业上的价值。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">2、未经</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>许可或者非为履行</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>职务的需要，</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>在任职期间或者离职后，不得擅自对前述载体进行复制，也不得将载体或者复制件遗弃、怠于保管或者交给他人。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">3、</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>应当于离职时，或者于</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>提出请求时，返还前述载体和复制件给</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>。当记录秘密信息的载体由</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>自备，且秘密信息可以从载体上消除或复制出来时，</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>应按</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>指令将秘密信息复制到</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>享有所有权的其他载体上，并把原载体上的秘密信息消除。此种情况下</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>无须将载体交给</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>，</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>也无须给予</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>任何经济补偿。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"></span>
</p>
<p class="p" style="text-align:center;background:#FFFFFF;" align="center">
  <b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>第三章</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;">&nbsp;&nbsp;</span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>职务成果</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;"></span></b>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">1、与</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>职务相关的智力成果，包括但不限于因履行职务、利用工作时间，或者利用</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>的物质技术条件等完成或者产生的任何发明创造、发现、研究、设计、改进、创新成果、作品、计算机软件、商业秘密等，以及由此获得的知识产权（含发明权、发现权、专利权和著作权等），均属于</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>所有；</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>可自由利用进行生产、经营或者转让给第三人。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">2、</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>有义务为职务成果保守秘密，并应当积极提供一切必要的信息和采取一切必要的行动（包括但不限于申请、注册、登记等），协助</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>取得和行使有关的知识产权或者所有权。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="text-align:center;background:#FFFFFF;" align="center">
  <b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>第四章</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;">&nbsp;&nbsp;</span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>保密制度</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;"></span></b>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">1、</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>应当遵守国家与</span></span><span style="font-family:等线;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>商业秘密保护</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>相关的法律、法规。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">2、</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>应当严格遵守</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>的任何成文或者不成文的保密制度，并履行与其工作岗位相应的保密职责。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">3、</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>的保密制度没有规定或者规定不明确之处，</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>亦应本着谨慎、诚信、负责的态度，采取必要和合理的措施，保守其知悉或者持有的商业秘密。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="text-align:center;background:#FFFFFF;" align="center">
  <b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>第五章</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;">&nbsp;&nbsp;</span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>保密责任</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;"></span></b>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">1、</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>不得以盗窃、利诱、胁迫或者其他不正当手段获取</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>商业秘密。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">2、未经</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>书面同意，</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>不得泄露、告知、公布、发表、出版、传播、传授、转让或者以遗弃或者怠于保管等其它任何方式使任何第三方（包括无权知悉该项商业秘密的</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>其他职员）知悉</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>商业秘密，也不得在履行职务之外使用这些商业秘密。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">3、</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>在任职期间，以及无论何种原因离职（含</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>或者</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>解除或者终止劳动合同）后，均应对其接触、知悉的</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>商业秘密，承担保密义务，直到</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>宣布解密或者有关秘密信息实际已经公开为止（但因</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>非正当公开的除外）。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">4、</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>承诺：在为</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>履行职务时，不得擅自使用任何属于他人的商业秘密，也不得擅自实施可能侵犯他人知识产权的行为。否则，导致</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>遭受第三人侵权指控，</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>因此而承担侵权赔偿责任的，有权向</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>追偿；同时</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>应当承担</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>为应诉而支付的一切费用。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">5、</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>认可所收取的劳动报酬已经考虑其任职期间或者离职后所承担的保密义务，并认可承担保密义务是其履行劳动合同的附随和法定义务，</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>无需另行支付保密费。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">6、</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>在任职期间或者离职后，均不得引诱</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>其他员工离职，否则视为侵犯</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>商业秘密。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="text-align:center;background:#FFFFFF;" align="center">
  <b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>第六章</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;">&nbsp;&nbsp;</span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>违约责任</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"></span></b>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">1、</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>违反</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>本协议</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>第四条（保密制度）、第五条（保密责任）规定的，属于</span>“严重违反</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>规章制度</span>”的行为，</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>有权单方与</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>即时解除劳动合同，并且不向</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>支付任何经济补偿。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">2、</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>违反</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>本协议</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>约定，或者侵犯</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>商业秘密的，应当对造成</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>的损失承担赔偿责任。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">3、</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>的损失，包括但不限于实际损失、间接损失（含预期利益）以及</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>因调查或制止</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>违约或者侵权行为而支付的合理费用（例如差旅费、鉴定费、诉讼费、仲裁费、律师费）等。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">4、</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>承担违约赔偿责任并不免除其继续按照</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>本协议</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>承担保密义务。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="text-align:center;background:#FFFFFF;" align="center">
  <b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>第七章</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;">&nbsp;&nbsp;</span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>争议解决</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;"></span></b>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">1、因履行</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>本协议</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>发生争议，由双方协商解决，协商不成的，</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您或者公司均有权</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>向</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>本协议签订地（上海市闵行区）</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>人民法院提起诉讼解决。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">2、前述约定不影响</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>请求知识产权管理部门对侵权行为进行处理。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;"></span>
</p>
<p class="p" style="text-align:center;background:#FFFFFF;" align="center">
  <b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>第八章</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;">&nbsp;&nbsp;</span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"><span>其它事项</span></span></b><b><span style="font-family:宋体;color:#2B2B2B;font-weight:bold;font-size:12.0000pt;background:#FFFFFF;"></span></b>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;">1、</span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>确认已经充分了解</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>有关保密的全部程序文件和管理规定，并自愿遵守执行。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>２、</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>本协议</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>是</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您与公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>签订</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>的</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>劳动合同的组成部分，</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>本协议</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>内容如与劳动合同或者</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>公司</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>规章制度不一致的，以</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>本协议</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>为准。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"></span>
</p>
<p class="p" style="background:#FFFFFF;">
  <span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>３、在</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>本协议</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>履行过程中相互发出或者提供的所有通知、文件等，均可以当面交付或以</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>您与公司签订的</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>《劳动合同书》列明的通讯地址履行送达义务；一方如果迁址或变更电话，应当及时书面通知对方；按前述地址的寄送无论对方拒收，或因地址不详等原因被退回的，均视为合法有效的送达。</span></span><span style="font-family:宋体;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"></span>
</p>
<p class="MsoNormal">
  <span style="font-family:等线;color:#2B2B2B;font-size:12.0000pt;background:#FFFFFF;"><span>（本页以下无正文）</span></span><span style="font-family:宋体;font-size:12.0000pt;"></span>
</p>